### PR TITLE
actually gate on heroku image

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4531a17 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4531a17 with merge e4072c9...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/docker/builds/126699857)

**Pull request merged**
