### PR TITLE
add rust image

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 97c4466 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 97c4466 with merge 97c4466...

**Comment by japaric** [comment]
@homunkulus r-

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a0cb67c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a0cb67c with merge 135dd41...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/docker/builds/127366729)

**Pull request merged**
