### PR TITLE
copper: add needed env vars

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+ p=1

**Comment by homunkulus** [comment]
:pushpin: Commit 771ebea has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 771ebea with merge 771ebea...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/docker/builds/127361091)

**Pull request merged**
