### PR TITLE
add heroku image

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b76ab7d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b76ab7d with merge 6aa74b8...

**Comment by homunkulus** [comment]
:hourglass: Testing commit b76ab7d with merge 4d7513f...

**Comment by homunkulus** [comment]
:hourglass: Testing commit b76ab7d with merge e99a0d0...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 10f1106 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 10f1106 with merge cdbe1c6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/docker/builds/126675504)

**Pull request merged**
